### ISSUE TITLE
Just lovely work

### ISSUE THREAD

**Issue by walterdavis** [rknightuk/lens#1]
No issue, just wanted to tell you I really appreciate this project and the care you invested in making it both useful and beautiful.

I would love it if there was a way to have it pre-load a site, perhaps with a ?url=[encoded url here] querystring. That would let me share a link to the analysis with someone less technical. Given that you've used a plain-old HTML file for the index page, that seems like it might need more JavaScript to check if there was a `window.location.search` that looked URL-shaped. I'll see if I can make that happen.

**Comment by rknightuk** [comment]
This was/is an excellent idea and was just a couple of lines of code to do (https://github.com/rknightuk/lens/commit/ec518832187b5fe6b253e5e1bbe97f6a2f5b5f00).

Thanks for suggesting it, this is now live on the site. Example: https://lens.rknight.me/?url=https://walterdavisstudio.com/
